---
 
- hosts: lamp_rocky
  become: true
  pre_tasks:
 
  - name: install updates (Rocky9)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes

   

- hosts: lamp_ubuntu
  become: true
  pre_tasks:
   
  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
   

    

- hosts: lamp_rocky
  become: true
  tasks:
 

  - name: install httpd, qemu guest agent, apache2, mariadb and php packages (Rocky9)
    tags: apache, centos, httpd, rocky 
    dnf:
      name:
        - httpd
        - php
        - php-gd
        - php-intl
        - php-ldap
        - php-opcache
        - php-mbstring
        - php-json
        - php-xml
        - qemu-guest-agent
        - mariadb-server        
      state: latest

  - name: start and enable httpd (Rocky9)
    tags: apache,rocky ,httpd
    service:
      name: httpd
      state: started
      enabled: yes

  - name: start and enable mariadb (Rocky9)
    tags: mariaddb,rocky
    service:
      name: mariadb
      state: started
      enabled: yes


- hosts: lamp_ubuntu
  become: true
  tasks:

  - name:  install apache2, mariadb and php packages on Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
        - mariadb-server
        - qemu-guest-agent
      state: latest
    when: ansible_distribution == "Ubuntu"     

