- hosts: all
  become: true
  pre_tasks:

  - name: update repository index (Rocky)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Rocky"

  - name: update repository index (Ubuntu)
    tags: always
    apt:
      update_cache: yes
      upgrade: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"