---

- hosts:  all
  become: true
  tasks:

  - name: update apt repository
    apt:
      update_cache: yes


  - name:  remove apache package
    apt:
      name: apache2
      state: absent

  - name: remove php support for apache
    apt:
      name: libapache2-mod-php
      state: absent