---
 
- hosts: all
  become: true
  pre_tasks:
 
  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
 
 
- hosts: lamp_servers
  become: true
  tasks:
 
  - name:  install qemu guest agent, apache2, mariadb and php packages on Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
        - php-gd
        - php-intl
        - php-ldap
        - php-opcache
        - php-mbstring
        - php-json
        - php-xml
        - qemu-guest-agent
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"
 
