- name: Deploy Wordpress 
  hosts: docker
  become: true 
  tasks:

    - name: Create Network
      community.docker.docker_network:
        name: wordpress

    - name: Deploy database
      community.docker.docker_container:
        name: db 
        image: mariadb:latest
        networks:
          - name: wordpress
        command: '--default-authentication-plugin=mysql_native_password'
        volumes:
          - db_data:/var/lib/mysql
        env:
          MYSQL_ROOT_PASSWORD: not2bright
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: not2bright
        state: started
        restart_policy: unless-stopped



    - name: Deploy wordpress
      community.docker.docker_container:
        name: wordpress
        image: wordpress:latest
        ports:
          - "8080:80"
        networks:
          - name: wordpress
        env: 
          WORDPRESS_DB_HOST: db
          WORDPRESS_DB_USER: wordpress
          WORDPRESS_DB_PASSWORD: not2bright
          WORDPRESS_DB_NAME: wordpress
        state: started
        restart_policy: unless-stopped