---

- hosts:  all
  become: true
  tasks:

  - name: update apt repository
    apt:
      update_cache: yes


  - name:  install apache2, mariadb and php packages on Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name:  install apache2, mariadb and php packages on Rocky
    dnf:
      name:
        - httpd
        - php
        - mariadb-server
      state: latest
    when: ansible_distribution == "Rocky"