---
 
- hosts: all
  become: true
  pre_tasks:
 
  - name: install updates (Rocky9)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Rocky"
 
  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
     src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
     dest: /usr/local/bin
     remote_src: yes
     mode: 0755
     owner: root
     group: root 

- hosts: web_servers
  become: true
  tasks:
 
  - name: install httpd package (Rocky9)
    tags: apache, rocky9, rocky, httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Rocky"

  - name: start and enable httpd (Rocky9)
    tags: apache,rocky ,httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "Rocky"
 
  - name: install apache2 package (Ubuntu)
    tags: apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
  
  - name: copy default html file for web site
    tags: apache, apache2, httpd
    copy: 
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
 
- hosts: db_servers
  become: true
  tasks:
 
  - name: install mariadb server package (Rocky)
    tags: db, database, mariadb, rocky9, rockyterra
    dnf:
       name: mariadb
       state: latest
    when: ansible_distribution == "Rocky"
 
  - name: install mariadb server
    tags: database, mariadb, ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba, ubuntu
    package:
      name: samba
      state: latest