---
 
- hosts: all
  become: true
  pre_tasks:
 
  - name: install updates (Rocky9)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Rocky9"
 
  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
 
 
- hosts: web_servers
  become: true
  tasks:
 
  - name: install httpd package (Rocky9)
    tags: apache, rocky9, rocky, httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Rocky9"
 
  - name: install apache2 package (Ubuntu)
    tags: apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
  
  - name: copy default html file for web site
    tags: apache, apache2, httpd
    copy: 
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
 
- hosts: db_servers
  become: true
  tasks:
 
  - name: install mariadb server package (Rocky9)
    tags: db, database, mariadb, rocky9, rockyterra
    dnf:
       name: mariadb
       state: latest
    when: ansible_distribution == "Rocky9"
 
  - name: install mariadb server
    tags: database, mariadb, ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba, ubuntu
    package:
      name: samba
      state: latest