---
 
- hosts: all
  become: true
  pre_tasks:
 
  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"
 
  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
 
 
- hosts: web_servers
  become: true
  tasks:
 
  - name: install httpd package (CentOS)
    tags: apache, centos, httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
 
  - name: install apache2 package (Ubuntu)
    tags: apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
 
- hosts: db_servers
  become: true
  tasks:
 
  - name: install mariadb server package (CentOS)
    tags: database, mariadb, centos
    dnf:
       name: mariadb
       state: latest
    when: ansible_distribution == "CentOS"
 
  - name: install mariadb server
    tags: database, mariadb, ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba, ubuntu
    package:
      name: samba
      state: latest